# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/williamstockhausen/Work/StockAssessments-Crab/AssessmentModelDevelopment/VS_Code/GMACS_tpl-cpp_code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/williamstockhausen/Work/StockAssessments-Crab/AssessmentModelDevelopment/VS_Code/GMACS_tpl-cpp_code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/williamstockhausen/Work/StockAssessments-Crab/AssessmentModelDevelopment/VS_Code/GMACS_tpl-cpp_code/CMakeFiles /Users/williamstockhausen/Work/StockAssessments-Crab/AssessmentModelDevelopment/VS_Code/GMACS_tpl-cpp_code//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/williamstockhausen/Work/StockAssessments-Crab/AssessmentModelDevelopment/VS_Code/GMACS_tpl-cpp_code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gmacs

# Build rule for target.
gmacs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmacs
.PHONY : gmacs

# fast build rule for target.
gmacs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/build
.PHONY : gmacs/fast

gmacs.o: gmacs.cpp.o
.PHONY : gmacs.o

# target to build an object file
gmacs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/gmacs.cpp.o
.PHONY : gmacs.cpp.o

gmacs.i: gmacs.cpp.i
.PHONY : gmacs.i

# target to preprocess a source file
gmacs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/gmacs.cpp.i
.PHONY : gmacs.cpp.i

gmacs.s: gmacs.cpp.s
.PHONY : gmacs.s

# target to generate assembly for a file
gmacs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/gmacs.cpp.s
.PHONY : gmacs.cpp.s

src/DatFileReader.o: src/DatFileReader.cpp.o
.PHONY : src/DatFileReader.o

# target to build an object file
src/DatFileReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/DatFileReader.cpp.o
.PHONY : src/DatFileReader.cpp.o

src/DatFileReader.i: src/DatFileReader.cpp.i
.PHONY : src/DatFileReader.i

# target to preprocess a source file
src/DatFileReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/DatFileReader.cpp.i
.PHONY : src/DatFileReader.cpp.i

src/DatFileReader.s: src/DatFileReader.cpp.s
.PHONY : src/DatFileReader.s

# target to generate assembly for a file
src/DatFileReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/DatFileReader.cpp.s
.PHONY : src/DatFileReader.cpp.s

src/dirichlet.o: src/dirichlet.cpp.o
.PHONY : src/dirichlet.o

# target to build an object file
src/dirichlet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/dirichlet.cpp.o
.PHONY : src/dirichlet.cpp.o

src/dirichlet.i: src/dirichlet.cpp.i
.PHONY : src/dirichlet.i

# target to preprocess a source file
src/dirichlet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/dirichlet.cpp.i
.PHONY : src/dirichlet.cpp.i

src/dirichlet.s: src/dirichlet.cpp.s
.PHONY : src/dirichlet.s

# target to generate assembly for a file
src/dirichlet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/dirichlet.cpp.s
.PHONY : src/dirichlet.cpp.s

src/equilibrium.o: src/equilibrium.cpp.o
.PHONY : src/equilibrium.o

# target to build an object file
src/equilibrium.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/equilibrium.cpp.o
.PHONY : src/equilibrium.cpp.o

src/equilibrium.i: src/equilibrium.cpp.i
.PHONY : src/equilibrium.i

# target to preprocess a source file
src/equilibrium.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/equilibrium.cpp.i
.PHONY : src/equilibrium.cpp.i

src/equilibrium.s: src/equilibrium.cpp.s
.PHONY : src/equilibrium.s

# target to generate assembly for a file
src/equilibrium.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/equilibrium.cpp.s
.PHONY : src/equilibrium.cpp.s

src/moltIncrement.o: src/moltIncrement.cpp.o
.PHONY : src/moltIncrement.o

# target to build an object file
src/moltIncrement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/moltIncrement.cpp.o
.PHONY : src/moltIncrement.cpp.o

src/moltIncrement.i: src/moltIncrement.cpp.i
.PHONY : src/moltIncrement.i

# target to preprocess a source file
src/moltIncrement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/moltIncrement.cpp.i
.PHONY : src/moltIncrement.cpp.i

src/moltIncrement.s: src/moltIncrement.cpp.s
.PHONY : src/moltIncrement.s

# target to generate assembly for a file
src/moltIncrement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/moltIncrement.cpp.s
.PHONY : src/moltIncrement.cpp.s

src/multinomial.o: src/multinomial.cpp.o
.PHONY : src/multinomial.o

# target to build an object file
src/multinomial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/multinomial.cpp.o
.PHONY : src/multinomial.cpp.o

src/multinomial.i: src/multinomial.cpp.i
.PHONY : src/multinomial.i

# target to preprocess a source file
src/multinomial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/multinomial.cpp.i
.PHONY : src/multinomial.cpp.i

src/multinomial.s: src/multinomial.cpp.s
.PHONY : src/multinomial.s

# target to generate assembly for a file
src/multinomial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/multinomial.cpp.s
.PHONY : src/multinomial.cpp.s

src/nloglike.o: src/nloglike.cpp.o
.PHONY : src/nloglike.o

# target to build an object file
src/nloglike.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/nloglike.cpp.o
.PHONY : src/nloglike.cpp.o

src/nloglike.i: src/nloglike.cpp.i
.PHONY : src/nloglike.i

# target to preprocess a source file
src/nloglike.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/nloglike.cpp.i
.PHONY : src/nloglike.cpp.i

src/nloglike.s: src/nloglike.cpp.s
.PHONY : src/nloglike.s

# target to generate assembly for a file
src/nloglike.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/nloglike.cpp.s
.PHONY : src/nloglike.cpp.s

src/robust_multi.o: src/robust_multi.cpp.o
.PHONY : src/robust_multi.o

# target to build an object file
src/robust_multi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/robust_multi.cpp.o
.PHONY : src/robust_multi.cpp.o

src/robust_multi.i: src/robust_multi.cpp.i
.PHONY : src/robust_multi.i

# target to preprocess a source file
src/robust_multi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/robust_multi.cpp.i
.PHONY : src/robust_multi.cpp.i

src/robust_multi.s: src/robust_multi.cpp.s
.PHONY : src/robust_multi.s

# target to generate assembly for a file
src/robust_multi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/robust_multi.cpp.s
.PHONY : src/robust_multi.cpp.s

src/spr.o: src/spr.cpp.o
.PHONY : src/spr.o

# target to build an object file
src/spr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/spr.cpp.o
.PHONY : src/spr.cpp.o

src/spr.i: src/spr.cpp.i
.PHONY : src/spr.i

# target to preprocess a source file
src/spr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/spr.cpp.i
.PHONY : src/spr.cpp.i

src/spr.s: src/spr.cpp.s
.PHONY : src/spr.s

# target to generate assembly for a file
src/spr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/spr.cpp.s
.PHONY : src/spr.cpp.s

src/tailcompression.o: src/tailcompression.cpp.o
.PHONY : src/tailcompression.o

# target to build an object file
src/tailcompression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/tailcompression.cpp.o
.PHONY : src/tailcompression.cpp.o

src/tailcompression.i: src/tailcompression.cpp.i
.PHONY : src/tailcompression.i

# target to preprocess a source file
src/tailcompression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/tailcompression.cpp.i
.PHONY : src/tailcompression.cpp.i

src/tailcompression.s: src/tailcompression.cpp.s
.PHONY : src/tailcompression.s

# target to generate assembly for a file
src/tailcompression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmacs.dir/build.make CMakeFiles/gmacs.dir/src/tailcompression.cpp.s
.PHONY : src/tailcompression.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gmacs"
	@echo "... gmacs.o"
	@echo "... gmacs.i"
	@echo "... gmacs.s"
	@echo "... src/DatFileReader.o"
	@echo "... src/DatFileReader.i"
	@echo "... src/DatFileReader.s"
	@echo "... src/dirichlet.o"
	@echo "... src/dirichlet.i"
	@echo "... src/dirichlet.s"
	@echo "... src/equilibrium.o"
	@echo "... src/equilibrium.i"
	@echo "... src/equilibrium.s"
	@echo "... src/moltIncrement.o"
	@echo "... src/moltIncrement.i"
	@echo "... src/moltIncrement.s"
	@echo "... src/multinomial.o"
	@echo "... src/multinomial.i"
	@echo "... src/multinomial.s"
	@echo "... src/nloglike.o"
	@echo "... src/nloglike.i"
	@echo "... src/nloglike.s"
	@echo "... src/robust_multi.o"
	@echo "... src/robust_multi.i"
	@echo "... src/robust_multi.s"
	@echo "... src/spr.o"
	@echo "... src/spr.i"
	@echo "... src/spr.s"
	@echo "... src/tailcompression.o"
	@echo "... src/tailcompression.i"
	@echo "... src/tailcompression.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

