project:
  output-dir: "../docs"
  type: website
  render: 
    - q01_Intro.qmd
    - q02-File-organization.qmd
    - q02a-gmacs-dat-file.qmd
    - q02b-model-dat-file.qmd
    - q02c-model-ctl-file.qmd
    - q02d-model-prj-file.qmd
  
website:
  sidebar:
    title: Contents
    background: primary
    search: true
    style: "docked"
    contents:
      - file: q01_Intro.qmd
      - file: q02-File-organization.qmd
      - file: q02a-gmacs-dat-file.qmd
      - file: q02b-model-dat-file.qmd
      - file: q02c-model-ctl-file.qmd
      - file: q02d-model-prj-file.qmd
  page-navigation: true
  page-footer: 
    right: "v.2.01.M.09"

format:
  html: 
    theme: cosmo
    toc: true
    html-math-method: mathjax
    code-block-bg: "#86CDFE"
    
bibliography: 
  - References/articles.bib
  - References/packages.bib

callout-icon: false

