---
title: "model.ctl file"
---

## General parameter specifications 
  * Initial: Initial value for the parameter (must lie between lower and upper)
  * Lower & Upper: Range for the parameter
  * Prior type
    - 0: Uniform   - parameters are the range of the uniform prior
    - 1: Normal    - parameters are the mean and sd
    - 2: Lognormal - parameters are the mean and sd of the log
    - 3: Beta      - parameters are the two beta parameters [see dbeta]
    - 4: Gamma     - parameters are the two gamma parameters [see dgamma]
  * Phase: Set equal to a negative number not to estimate
  * Relative: 0: absolute; 1 relative 
  * Block: Block group number for time variation   
  * Block_fn: 
    - 0: absolute values
    - 1: exponential
  * Env_L: Environmental link
    - 0: none
    - 1: additive
    - 2: multiplicative
    - 3: exponential
  * EnvL_var: Environmental variable
  * RW: random walk characteristics
    - 0 for no random walk changes
    - 1 otherwise
  * RW_blk: Block number for random walks
  * Sigma_RW: Sigma used for the random walk

## options and flags

### Prior types
  * 0: Uniform   - parameters are the range of the uniform prior
  * 1: Normal    - parameters are the mean and sd
  * 2: Lognormal - parameters are the mean and sd of the log
  * 3: Beta      - parameters are the two beta parameters [see dbeta]
  * 4: Gamma     - parameters are the two gamma parameters [see dgamma]

### Initial N
  * 0: unfished equilibrium (UNFISHEDEQN)
  * 1: fished equilibrium (FISHEDEQN)
  * 2: freely-estimated parameters (FREEPARS)
  * 3: freely-estimated parameters (scaled) (FREEPARSSCALED)
  * 4: reference points (??) (REFPOINTS)

### Allometry: Length-weight relationships
  * 1: functional relationship (LW_RELATIONSHIP)
  * 2: vector of values        (LW_VECTOR)
  * 3: matrix (rows: years; columns: sizes) (LW_MATRIX)

### Natural mortality (M) flags
  * 0: constant M (M_CONSTANT)
  * 1: random (walk?) (M_RANDOM)
  * 2: cubic spline (M_CUBIC_SPLINE)
  * 3: blocked changes (M_BLOCKED_CHANGES)
  * 4: time blocks type 1 (M_TIME_BLOCKS1)
  * 5: time blocks type 3 (M_TIME_BLOCKS3)
  * 6: time blocks type 2 (M_TIME_BLOCKS2) [yes, out of order]

#### Custom M
  * 0: no custom M      (NO_CUSTOM_M)
  * 1: w/ custom M (??) (WITH_CUSTOM_M)

### Growth transition types
#### Options for the growth matrix
  * 1: Pre-specified growth transition matrix (requires molt probability)
  * 2: Pre-specified size transition matrix (molt probability is ignored)
  * 3: Growth increment is gamma distributed (requires molt probability)
  * 4: Post-molt size is gamma distributed (requires molt probability)
  * 5: Von Bert.: kappa varies among individuals (requires molt probability)
  * 6: Von Bert.: Linf varies among individuals (requires molt probability)
  * 7: Von Bert.: kappa and Linf varies among individuals (requires molt probability)
  * 8: Growth increment is normally distributed (requires molt probability)

#### Options for the growth increment model matrix
  * 1: Linear 
    - intercept
    - slope
    - ln-scale gamma distribution scale parameter
  * 2: Individual
  * 3: Individual (Same as 2)
  * 4: Power law for mean post-molt size 
    - ln-scale intercept
    - ln-scale slope
    - ln-scale gamma distribution scale parameter
  * 5: Alternative power law for mean post-molt size. 
    - reference (small) pre-molt size (constant: must have phase < 0)
    - mean post-molt size at small reference pre-molt size
    - reference (large) pre-molt size (constant: must have phase < 0)
    - mean post-molt size at large reference pre-molt size
    - ln-scale gamma distribution scale parameter

##### Options for the molt probability function
  * 0: Pre-specified (FIXED_PROB_MOLT)
  * 1: Constant at 1 (CONSTANT_PROB_MOLT)
  * 2: Logistic      (LOGISTIC_PROB_MOLT)
  * 3: Individual    (FREE_PROB_MOLT)

##### Options for the mature probability function
  * 0: Pre-specified (FIXED_PROB_MATURE)
  * 1: Constant at 1 (CONSTANT_PROB_MATURE)
  * 2: Logistic      (LOGISTIC_PROB_MATURE)
  * 3: Individual    (FREE_PROB_MATURE)

### Fishing mortality type flags
  * 0: inatantaneous F (INSTANT_F)
  * 1: constinuous F   (CONTINUOUS_F)
  * 2: ??              (EXPLOIT_F)

#### Selectivity and retention function flags
  * 0: Parametric selectivity    (SELEX_PARAMETRIC)
  * 1: coefficients              (SELEX_COEFFICIENTS)
  * 2: standard logistic         (SELEX_STANLOGISTIC)
    - ln-scale size-at-50% selected
    - ln-scale "width" (1/"slope") 
  * 3: alternative logistic      (SELEX_5095LOGISTIC)
    - size-at-50% selected
    - size at 95% selected
  * 4: double normal             (SELEX_DOUBLENORM)
  * 5: uniform with value 1      (SELEX_UNIFORM1)
  * 6: uniform with value 0      (SELEX_UNIFORM0)
  * 7: 4-parameter double normal (SELEX_DOUBLENORM4)
  * 8: declining logistic        (SELEX_DECLLOGISTIC)
  * 9: cubic spline              (SELEX_CUBIC_SPLINE)
  * 10: 1-paameter logistic      (SELEX_ONE_PAR_LOGISTIC)
  * 11: pre-specified            (SELEX_PRESPECIFIED)
  * 12: cubic spline w/ a floor  (SELEX_CUBIC_SPLINE_FLOOR)
  * 13 stacked logistic          (SELEX_STACKED_LOGISTIC)

## `The model.ctl` file {#sec-model-ctl-file}

While the file is a single entity, it is convenient to examine the different sections separately in the order they occur in the file (see below). 

Values are separated by spaces or tabs. Character-based input (e.g., fleet names, etc.) should not contain spaces, tabs, or "#", but can contain numbers and punctuation. An underscore ("_") is used to indicate a space--underscores will be replaced by spaces in formatted model output (e.g., in tables or figures). 
::: {#nte-ctl1 .callout-note title="Theta parameter section of example `model.ctl` file."}

```default
## ———————————————————————————————————————————————————————————————————————————————————— ##                                          
## LEADING PARAMETER CONTROLS                                                           ##                                          
##     Controls for leading parameter vector (theta)                                    ##                                          
## LEGEND                                                                               ##                                          
##     prior: 0 = uniform, 1 = normal, 2 = lognormal, 3 = beta, 4 = gamma               ##"                                          
## ———————————————————————————————————————————————————————————————————————————————————— ##                                          
## ntheta                                          
100                                          
## ———————————————————————————————————————————————————————————————————————————————————— ##                                          
## ival   lb      ub        phz   prior   p1       p2         # parameter       ##                                          
## ———————————————————————————————————————————————————————————————————————————————————— ##                                          
  0.271   0.15    0.7       4       1    0.271    0.00454    # M (male)                                          
  0.271   0.15    0.7       4       1    0.271    0.00454    # M (female)                                          
 16.5   -10      20        -2       0  -10.0    20.0         # logR0                                          
 15.0   -10      30        -1       0   10.0    20.0         # logRini, to estimate if NOT initialized at unfished (n68)"                                          
 13.26  -10      30         1       0   10.0    20.0         # logRbar, to estimate if NOT initialized at unfished      #1"                                          
 32.5     7.5    42.5      -4       0   32.5     2.25        # recruitment expected value (males or combined)                                          
  1.0     0.1    10        -4       0    0.1     5.0         # recruitment scale (variance component) (males or combined)                                        
  0.0   -10      10        -4       0    0.0     20.00       # recruitment expected value (females)                                          
  0.00  -10      10        -3       0    0.0    20.0         # recruitment scale (variance component) (females)                                        
 -0.9   -10       0.75     -4       0  -10.0     0.75        # ln(sigma_R)                                          
  0.75    0.20    1.00     -2       3    3.0     2.00        # steepness                                          
  0.01    0.0001  1.00     -3       3    1.01    1.01        # recruitment autocorrelation                                          
  0.0   -10      25         1       0   10.0    20.00        # Deviation for size-class 1  # mature males  (normalization class)                                
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 2                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 3                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 4                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 5                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 6                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 7                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 8                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 9                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 10                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 11                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 12                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 13                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 14                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 15                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 16                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 17                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 18                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 19                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 20                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 21                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 22                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 1                                           
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 2  # immature males                                  
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 3                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 4                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 5                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 6                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 7                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 8                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 9                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 10                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 11                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 12                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 13                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 14                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 15                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 16                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 17                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 18                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 19                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 20                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 21                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 22                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 1  # mature females                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 2                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 3                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 4                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 5                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 6                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 7                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 8                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 9                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 10                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 11                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 12                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 13                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 14                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 15                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 16                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 17                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 18                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 19                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 20                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 21                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 22                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 1   # immature females                                
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 2                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 3                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 4                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 5                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 6                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 7                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 8                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 9                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 10                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 11                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 12                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 13                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 14                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 15                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 16                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 17                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 18                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 19                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 20                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 21                                    
  0.0   -20      25         1       0   10.0    20.00        # Deviation for size-class 22                                    
```

::: 


::: {#nte-ctl2 .callout-note title="Weight-at-length and Proportions mature/legal section of example `model.ctl` file."}

```default
#  weight-at-length input  method  (1 = allometry  "[w_l = a*l^b],"  2 = vector by sex)                                
2                                          
##  Males                                        
7.66E-06  1.29E-05  2.00E-05  2.95E-05  4.17E-05  5.68E-05  7.53E-05  0.000097455  0.000123688  0.000154329  0.000189739  0.000230279  0.000276313  0.000328208  0.000386333  0.000451057  0.000522754  0.000601796  0.000688561  0.000783424  0.000886766  0.000998966
7.66E-06  1.29E-05  2.00E-05  2.95E-05  4.17E-05  5.68E-05  7.53E-05  0.000097455  0.000123688  0.000154329  0.000189739  0.000230279  0.000276313  0.000328208  0.000386333  0.000451057  0.000522754  0.000601796  0.000688561  0.000783424  0.000886766  0.000998966
## Females                                          
9.17E-06  1.44E-05  2.13E-05  2.98E-05  4.03E-05  5.29E-05  6.77E-05  0.000084796  0.000104451  0.000126759  0.000151857  0.000179881  0.000210963  0.000245233  0.00028282  0.00032385  0.000368446  0.000416731  0.000468827  0.000524852  0.000584924  0.00064916
9.17E-06  1.44E-05  2.13E-05  2.98E-05  4.03E-05  5.29E-05  6.77E-05  0.000084796  0.000104451  0.000126759  0.000151857  0.000179881  0.000210963  0.000245233  0.00028282  0.00032385  0.000368446  0.000416731  0.000468827  0.000524852  0.000584924  0.00064916
# Proportion mature by sex                                          
0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1
0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
# Proportion legal by sex                                          
0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1
0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
# use functional maturity for terminally molting animals?
0
```

::: 


::: {#nte-ctl3 .callout-note title="Growth parameter section of example `model.ctl` file."}

```default
## ———————————————————————————————————————————————————————————————————————————————————— ##
## GROWTH PARAMETER CONTROLS                                                            ##
##     Two lines for each parameter if split sex, one line if not                       ##
##     Currently if growth parameters change, moltin gprobabilities also must"          ##
## ———————————————————————————————————————————————————————————————————————————————————— ##
# Use growth transition matrix options 
##  1 = read in growth-increment matrix; 
##  2 = read in size-transition; 
##  3 = gamma distribution for size-increment; 
##  4 = gamma distribution for size after increment
4                                          
# growth increment model (1=alpha/beta; 2=estimated by size-class;3=pre-specified/emprical)
1                                          
# molt probability function (0=pre-specified; 1=flat;2=declining logistic; 3=free parameters)
0                                          
# Maximum size-class for recruitment(males then females)                        
3 3                                           
## number of size-increment periods                                          
1 1                                          
## Year(s) size-incremnt period changes (blank if no changes)                   

## number of molt periods                                          
42 42                                          
## Year(s) molt period changes (blank if no changes)                            
  1983  1984  1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021  2022 2023
  1983  1984  1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021  2022 2023
## Beta parameters are relative (1=Yes;0=no)                                    
0                                          
## ———————————————————————————————————————————————————————————---## 
## ival       lb  ub   phz  prior p1    p2    # parameter        ## 
## ——————————————————————————————————————————————————————————————## 
  2.049    -5     20    3    1  2.05    1    # Males alpha        
  -0.2258  -1      0    3    1 -0.22    0.5  # Males beta       
   0.25     0.001  5   -3    0  0     999    # Males scale        
  -1.1539  -5     10    3    1 -1.15    1    # Females alpha        
  -0.3389  -1      0    3    1 -0.34    0.5  # Females beta        
   0.25     0.001  5   -3    0  0     999    # Females scale        
## ———————————————————————————————————————————————————————————————————————————————————- ##  
## ———————————————————————————————————————————————————————————————————————————————————— ## 
## MOLTING PROBABILITY CONTROLS                                                         ## 
##     Two lines for each parameter if split sex, one line if not                       ## 
##     If free molting probability, list a probability for each size class and sex
##     iF PRE-specified, matrices by sex, with rows as year and columns as size           
## ———————————————————————————————————————————————————————————————————————————————————— ## 
## ival       lb        ub        phz   prior     p1      p2          # parameter       ##  
## ———————————————————————————————————————————————————————————————————————————————————— ##  
## MALES
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.006  0.017  0.051  0.106  0.149  0.178  0.181  0.156  0.193  0.293  0.406  0.532  0.669  0.815  0.914  0.968  0.993  0.987  0.989  0.996
0.000  0.000  0.001  0.003  0.022  0.058  0.092  0.124  0.191  0.295  0.355  0.371  0.379  0.377  0.436  0.557  0.693  0.844  0.940  0.980  1.000  1.000
0.000  0.000  0.001  0.002  0.017  0.045  0.091  0.154  0.204  0.239  0.268  0.291  0.302  0.300  0.409  0.630  0.800  0.918  0.977  0.976  0.982  0.994
0.000  0.000  0.004  0.011  0.058  0.144  0.203  0.236  0.299  0.391  0.452  0.482  0.519  0.565  0.662  0.812  0.913  0.967  0.995  0.998  1.000  1.000
0.000  0.000  0.005  0.014  0.037  0.074  0.144  0.247  0.388  0.564  0.663  0.685  0.708  0.732  0.796  0.900  0.960  0.976  0.988  0.996  1.000  1.000
0.000  0.000  0.010  0.029  0.058  0.098  0.151  0.217  0.301  0.404  0.477  0.519  0.534  0.522  0.600  0.767  0.883  0.949  0.986  0.995  1.000  1.000
0.000  0.000  0.005  0.014  0.041  0.084  0.127  0.168  0.237  0.332  0.424  0.511  0.588  0.655  0.725  0.797  0.871  0.945  0.980  0.974  0.979  0.993
0.000  0.000  0.000  0.000  0.035  0.105  0.152  0.175  0.228  0.311  0.373  0.414  0.450  0.481  0.595  0.794  0.908  0.940  0.967  0.989  1.000  1.000
0.000  0.000  0.002  0.006  0.034  0.084  0.129  0.170  0.209  0.248  0.265  0.261  0.293  0.362  0.485  0.663  0.807  0.919  0.981  0.994  1.000  1.000
0.000  0.000  0.005  0.015  0.046  0.099  0.149  0.194  0.267  0.367  0.408  0.389  0.406  0.460  0.579  0.762  0.882  0.939  0.973  0.986  0.994  0.998
0.000  0.000  0.023  0.068  0.117  0.170  0.223  0.276  0.349  0.445  0.469  0.422  0.456  0.572  0.699  0.835  0.917  0.944  0.968  0.989  1.000  1.000
0.000  0.000  0.004  0.011  0.028  0.055  0.126  0.242  0.324  0.374  0.401  0.406  0.453  0.545  0.677  0.851  0.946  0.963  0.978  0.993  1.000  1.000
0.000  0.000  0.000  0.000  0.033  0.099  0.142  0.161  0.200  0.260  0.332  0.416  0.492  0.559  0.672  0.832  0.923  0.945  0.967  0.989  1.000  1.000
0.000  0.000  0.000  0.000  0.007  0.021  0.087  0.203  0.288  0.341  0.359  0.342  0.370  0.443  0.580  0.782  0.913  0.971  1.000  1.000  1.000  1.000
0.000  0.000  0.013  0.040  0.072  0.110  0.149  0.189  0.222  0.251  0.291  0.344  0.369  0.366  0.468  0.677  0.820  0.898  0.926  0.904  0.919  0.973
0.000  0.000  0.000  0.000  0.037  0.112  0.190  0.270  0.351  0.431  0.533  0.656  0.684  0.617  0.633  0.734  0.828  0.914  0.968  0.989  1.000  1.000
0.000  0.000  0.014  0.043  0.078  0.119  0.165  0.216  0.295  0.401  0.485  0.547  0.555  0.508  0.594  0.813  0.933  0.952  0.968  0.981  0.990  0.997
0.000  0.000  0.019  0.057  0.095  0.133  0.222  0.360  0.434  0.443  0.442  0.430  0.478  0.588  0.672  0.731  0.808  0.902  0.962  0.987  1.000  1.000
0.000  0.000  0.000  0.000  0.032  0.097  0.204  0.355  0.459  0.514  0.531  0.507  0.485  0.465  0.555  0.754  0.868  0.897  0.867  0.779  0.801  0.934
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.000  0.000  0.100  0.300  0.388  0.363  0.359  0.376  0.348  0.275  0.208  0.149  0.245  0.496  0.716  0.905  1.000  1.000  1.000  1.000
0.000  0.000  0.001  0.002  0.025  0.071  0.176  0.342  0.476  0.579  0.624  0.611  0.680  0.833  0.925  0.956  0.964  0.949  0.957  0.986  1.000  1.000
0.000  0.000  0.000  0.000  0.031  0.094  0.133  0.146  0.256  0.461  0.544  0.505  0.483  0.481  0.610  0.870  1.000  1.000  0.964  0.893  0.893  0.964
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.000  0.000  0.016  0.049  0.124  0.243  0.357  0.466  0.530  0.550  0.600  0.680  0.770  0.871  0.932  0.953  0.972  0.991  1.000  1.000
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.000  0.000  0.031  0.093  0.190  0.321  0.420  0.488  0.534  0.556  0.572  0.581  0.683  0.877  0.981  0.994  1.000  1.000  1.000  1.000
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.009  0.028  0.104  0.237  0.309  0.321  0.355  0.410  0.480  0.563  0.662  0.778  0.865  0.922  0.961  0.980  0.992  0.997  1.000  1.000
0.000  0.000  0.008  0.023  0.066  0.136  0.232  0.354  0.442  0.497  0.572  0.665  0.757  0.849  0.918  0.965  0.991  0.997  1.000  1.000  1.000  1.000
0.000  0.000  0.042  0.125  0.162  0.154  0.170  0.209  0.244  0.273  0.320  0.386  0.519  0.718  0.835  0.870  0.909  0.952  0.980  0.993  1.000  1.000
0.000  0.000  0.010  0.029  0.067  0.123  0.184  0.250  0.321  0.396  0.445  0.467  0.503  0.551  0.648  0.795  0.893  0.945  0.973  0.977  0.984  0.995
0.000  0.000  0.111  0.334  0.477  0.540  0.574  0.579  0.574  0.560  0.561  0.577  0.612  0.664  0.757  0.893  0.971  0.990  1.000  1.000  1.000  1.000
0.000  0.000  0.003  0.008  0.037  0.090  0.159  0.245  0.392  0.598  0.663  0.585  0.565  0.603  0.687  0.815  0.900  0.941  0.972  0.991  1.000  1.000
0.000  0.005  0.022  0.047  0.081  0.126  0.182  0.248  0.320  0.396  0.471  0.544  0.619  0.695  0.770  0.838  0.896  0.941  0.973  0.994  1.000  1.000
## FEMALES
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
0.0061  0.0189  0.0584  0.1775  0.4667  0.7761  0.8119  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999  0.9999
## ———————————————————————————————————————————————————————————————————————————————————— ##  
##   ival     lb         ub      phz   prior   p1      p2          # parameter          ##  
## ———————————————————————————————————————————————————————————————————————————————————— ##  
## males and combined                                          
##   90.0386  20.      200.0      2       0    0.0    999.0         # molt_mu males
##    0.1      0.0001    2.0      2       0    0.0    999.0         # molt_cv males 
## females                                          
##  50.0000    5.      200.0      2       0    0.0    999.0         # molt_mu females
##   0.001     0.0001    9.0      2       0    0.0    999.0         # molt_cv females
## ——————————————————————————————————————————————————————————————————————————————————— ## 
## ——————————————————————————————————————————————————————————————————————————————————— ## 
# custom growth-increment matrix (if any)  
NEED EXAMPLE
# custom molt probability matrix (if any)  
NEED EXAMPLE
```

::: 


::: {#nte-ctl4 .callout-note title="Selectivity parameter section of example `model.ctl` file."}

```default
## ———————————————————————————————————————————————————————————————————————————————————— ##
## SELECTIVITY CONTROLS                                                                 ##
##     Selectivity P(capture of all sizes). Each gear must have a selectivity and a     ##
##     retention selectivity. If a uniform prior is selected for a parameter then the   ##
##     lb and ub are used (p1 and p2 are ignored)                                       ##
## LEGEND                                                                               ##
##     sel type: 0 = parametric, 1 = coefficients (NIY), 2 = logistic, 3 = logistic95,  ##
##               4 = double normal (NIY)                                                ##
##     gear index: use +ve for selectivity, -ve for retention                           ## 
##     sex dep: 0 for sex-independent, 1 for sex-dependent                              ##
## ———————————————————————————————————————————————————————————————————————————————————— ##
## Gear-1   Gear-2   Gear-3  Gear-4
## PotFshry TrawlByc NMFS    NMFS    
   1        1        1       1       # selectivity periods
   1        0        1       1       # sex specific selectivity
   2        2        0       0       # male selectivity type (slx_type_in, to mirror, make negative and equal to the fleet to be mirrored)
   2        2        0       0       # female selectivity type
   0        0        0       0       # within another gear  
   0        0        0       0       # extra parameters for each pattern by fleet (males)
   0        0        0       0       # extra parameters for each pattern by fleet (females)
## Gear-1   Gear-2   Gear-3  Gear-4                                        
   1        1        1       1       # retention periods                        
   1        0        0       0       # sex specific retention                   
   2        6        6       6       # male   retention type                   
   6        6        6       6       # female retention type                    
   1        0        0       0       # male   retention flag (0 = no, 1 = yes)
   0        0        0       0       # female retention flag (0 = no, 1 = yes)
   0        0        0       0       # extra parameters for each pattern by fleet (males)
   0        0        0       0       # extra parameters for each pattern by fleet (females)
   1        1        0       0       # determines if maximum selectivity at size is forced to equal 1 or not
## ———————————————————————————————————————————————————————————-------————————————————————————-————————————————————————-——————— ##
## gear  par   sel                                             start  end     Env  Link  Rand  Start_Y  End_Y   Sigma          ##
## index index par sex  ival    lb  ub  prior  p1 p2     phz   period period  Link  Par  Walk  period  period                  ##
## ——————————————————————————————————————————————————————————————————————————————————————————-————————————————————————-——————— ##
# Gear-1                                          
   1      1    1   1  105.71   5    186    0    1 999    4    1982    2023     0    0     0      0       0      0
   1      2    2   1    4.99   0.01  20    0    1 999    4    1982    2023     0    0     0      0       0      0 
   1      3    1   2   74.85   5    150    0    1 999    4    1982    2023     0    0     0      0       0      0
   1      4    2   2    4.18   0.01  20    0    1 999    4    1982    2023     0    0     0      0       0      0
# Gear-2   
   2      5    1   0  109.93   5    185    0    1 999    4    1982    2023 0  0  0  0  0   0 
   2      6    2   0   11.86   0.01  20    0    1 999    4    1982    2023 0  0  0  0  0   0 
...

```

::: 


::: {#nte-ctl6 .callout-note title="Retention curve section of example `model.ctl` file."}

```default
## ———————————————————————————————————————————————————————————————————————————————————— ##
## Retained                                                                             ## 
## ———————————————————————————————————————————————————————————-------————————————————————————-————————————————————————-—————##
## gear  par   sel                                                  start  end    Env  Link Rand  Start_Y  End_Y   Sigma    ##
## index index par sex  ival    lb     ub   prior p1   p2    phz   period period  Link Par  Walk  period  period            ##
## ——————————————————————————————————————————————————————————————————————————————————————————-————————————————————————-—————##
# Gear-1                                          
  -1     61    1   1   96.03    1      190    1   96   10    4     1982   2022     0    0    0      0       0      0
  -1     62    2   1    2.19    0.001   20    0    1  999    4     1982   2022     0    0    0      0       0      0 
  -1     63    1   2    595     1      999    0    1  999   -3     1982   2022     0    0    0      0       0      0
# Gear-2                                                                                             
  -2     64    1   0    595     1      999    0    1  999   -3     1982   2022     0    0    0      0       0      0
# Gear-3                                                                                            
  -3     65    1   0    595     1      999    0    1  999   -3     1982   2022     0    0    0      0       0      0
# Gear-4                                                                                            
  -4     66    1   0    595     1      999    0    1  999   -3     1982   2022     0    0    0      0       0      0
## ———————————————————————————————————————————————————————————————————————————————————— ##           
# Number of asymptotic parameters                                          
0                                          
# Fleet  Sex  Year    ival     lb   ub    phz    
#   1     1   1982   0.000001   0    1     -3    
# Deviation parameter phase
-1                                      
```

::: 


::: {#nte-ctl7 .callout-note title="Survey catchability section of example `model.ctl` file."}

```default
## ———————————————————————————————————————————————————————————————————————————————————— ##
## PRIORS FOR CATCHABILITY                                          
##     If a uniform prior is selected for a parameter then the lb and ub are used (p1   ##
##     and p2 are ignored). ival must be > 0                                            ##
## LEGEND                                                                               ##
##     prior: 0 = uniform, 1 = normal, 2 = lognormal, 3 = beta, 4 = gamma               ##
## ———————————————————————————————————————————————————————————————————————————————————— ##
## ival   lb    ub    phz   prior    p1      p2   Analytic? LAMBDA Emphasis               
   1     0.01  1.01   -5       0  0.843136  0.03     0        1       1   # NMFS_TRAWL_1982 FEMALES
   1     0.01  1.01   -5       0  0.843136  0.03     0        1       1   # NMFS_TRAWL_1989 FEMALES
   1     0.01  1.01   -5       0  0.45136   0.5      0        1       1   # NMFS_TRAWL_1982 MALES 
   1     0.01  1.01   -5       0  0.453136  0.5      0        1       1   # NMFS_TRAWL_1989 MALES
## ———————————————————————————————————————————————————————————————————————————————————— ##
```

::: 


::: {#nte-ctl8 .callout-note title="Additional CV section of example `model.ctl` file."}

```default
## ———————————————————————————————————————————————————————————————————————————————————— ##
## ADDITIONAL CV FOR SURVEYS/INDICES                                                    ##
##     If a uniform prior is selected for a parameter then the lb and ub are used (p1   ##
##     and p2 are ignored). ival must be > 0                                            ##
## LEGEND                                                                               ##
##     prior type: 0 = uniform, 1 = normal, 2 = lognormal, 3 = beta, 4 = gamma          ##
## ———————————————————————————————————————————————————————————————————————————————————— ##
## ival        lb        ub        phz   prior     p1      p2                          
   0.0001      0.00001   10.0      -4    0         1.0     100   # NMFS  era 1         
   0.0001      0.00001   10.0      -4    0         1.0     100   # NMFS  era 2
   0.0001      0.00001   10.0      -4    0         1.0     100   # NMFS  era 1         
   0.0001      0.00001   10.0      -4    0         1.0     100   # NMFS  era 2 
### Pointers to how the the additional CVs are used (0 ignore; >0 link to one of the parameters
 0 0 0 0
####
```

::: 


::: {#nte-ctl9 .callout-note title="Penalties on average fishing mortality rates section of example `model.ctl` file."}

```default
## ———————————————————————————————————————————————————————————————————————————————————— ##
## ———————————————————————————————————————————————————————————————————————————————————— ##
## PENALTIES FOR AVERAGE FISHING MORTALITY RATE FOR EACH GEAR                             
## ———————————————————————————————————————————————————————————————————————————————————— ##
## Mean_F   Female Offset STD_PHZ1   STD_PHZ2   PHZ_M   PHZ_F                           
   1           0.0505      0.5        45.50      1       1     -12  4  -10     10     -10    10  # Pot
   0.018       1.0         0.5        45.50      1      -1     -12  4  -10     10     -10    10   # Trawl
   0.00        0.0         2.0        20.00     -1      -1     -12  4  -10     10     -10    10   # NMFS trawl survey era 1 (0 catch)
   0.00        0.0         2.0        20.00     -1      -1     -12  4  -10     10     -10    10   # NMFS trawl survey era 2 (0 catch)
## ———————————————————————————————————————————————————————————————————————————————————— ##
```

::: 


::: {#nte-ctl10 .callout-note title="Options for size compositions section of example `model.ctl` file."}

```default
# ——————————————————————————————————————————————————————————————————————————————##
## OPTIONS FOR SIZE COMPOSTION DATA                                             ##
##     One column for each data matrix                                          ##
## LEGEND                                                                       ##
##     Likelihood: 1 = Multinomial with estimated/fixed sample size             ##
##                 2 = Robust approximation to multinomial                      ##
##                 3 = logistic normal (NIY)                                    ##
##                 4 = multivariate-t (NIY)                                     ##
##                 5 = Dirichlet                                                ##
## AUTO TAIL COMPRESSION                                                        ##
##     pmin is the cumulative proportion used in tail compression               ##
## —————————————————————————————————————————————————————————————————————————————##
#  Pot         Trawl   NMFS                                              
   2   2   2   2   2   2   2   2   2  2   2   2   2   # Type of likelihood  
   0   0   0   0   0   0   0   0   0  0   0   0   0   # Auto tail compression (pmin)
   1   1   1   1   1   1   1   1   1  1   1   1   1   # Initial value for effective sample size multiplier  
  -4  -4  -4  -4  -4  -4  -4  -4  -4  -4  -4  -4  -4  # Phz for estimating effective sample size (if appl.) 
   1   2   3   4   5   6   7   8   9  10  11  12  13  # Composition splicer
   1   1   1   1   1   2   2   2   2  2   2   2   2   # Set to 2 for survey-like predictions; 1 for catch-like predictions
   1   1   1   1   1   1   1   1   1  1   1   1   1   # LAMBDA                  
   1   1   1   1   1   1   1   1   1  1   1   1   1   # Emphasis AEP            
## ——————————————————————————————————————————————————————————————————————————————##
```

::: 


::: {#nte-ctl11 .callout-note title="Time-varying natural mortality parameter section of example `model.ctl` file."}

```default
## ———————————————————————————————————————————————————————————————————————————————————— ##
## TIME VARYING NATURAL MORTALIIY RATES                                                 ##
## LEGEND                                                                               ##
## Type: 0 = constant natural mortality                                                 ##
##       1 = Random walk (deviates constrained by variance in M)                        ##
##       2 = Cubic Spline (deviates constrained by nodes & node-placement)              ##
##       3 = Blocked changes (deviates constrained by variance at specific knots)       ##
##       4 = Time blocks                                                                ##
## ———————————————————————————————————————————————————————————————————————————————————— ##
## Type                                          
6
# 0
## M is relative (YES=1; NO=0)                                          
0                                          
## Phase of estimation                                          
4
# -3
## STDEV in m_dev for Random walk                                          
2
# 0.25
## Number of nodes for cubic spline or number of step-changes for option 3     
3
3
# 0
## Year position of the knots (vector must be equal to the number of nodes)
2018 2019 2020
2018 2019 2020
# 0
# number of breakpoints in M by size                                          
0                                          
#                                           
## Specific initial values for the natural mortality devs (0-no, 1=yes)"
1  
## —————————————————————————————————————————————————————————————————————————————##
## ival     lb  ub  phz  extra  prior  p1  p2  # parameter 
## —————————————————————————————————————————————————————————————————————————————##
 1.000000   0   9   4      0                                        
 1.000000   0   9   4      0
 0.000010   0   9  -4      0                                        
 1.000000   0   9   4      0                                        
 1.000000   0   9   4      0
 0.000010   0   9  -4      0                                        
 1.000000   0   9   4      0                                        
 1.000000   0   9   4      0
 0.000010   0   9  -4      0                                        
 1.000000   0   9   4      0                                        
 1.000000   0   9   4      0  
 0.000010   0   9  -4      0                                        
## —————————————————————————————————————————————————————————————————————————————-##
```

::: 


::: {#nte-ctl12 .callout-note title="Tagging controls parameter section of example `model.ctl` file."}

```default
##  ————————————————————————————————————————————————————————————————————————————##
##  TAGGING controls  CONTROLS
##  ————————————————————————————————————————————————————————————————————————————##
1          # emphasis on tagging data
## —————————————————————————————————————————————————————————————————————————————##
NEED EXAMPLE

```

::: 


::: {#nte-ctl13 .callout-note title="Maturity specific natural mortality parameter section of example `model.ctl` file."}

```default
## ————————————————————————————————————————————————————————————————————————---##  
## Maturity specific natural mortality
## ———————————————————————————————————————————————————————————————————————————##  
# maturity specific natural mortality? (yes = 1; no = 0; only for use if nmature > 1)
1                                        
## —————————————————————————————————————————————————————————————————————————-##                 
## ival    lb     ub    phz   prior  p1      p2   # parameter                ##
## ——————————————————————————————————————————————————————————————————————————##                 
 0.00      -4     4     4       1    0     0.05   # offset for immature male natural mortality    
 0.00      -4     4     4       1    0     0.05   # offset for immature female natural mortality  
## ———————————————————————————————————————————————————————————————————————————————————— ##       
```

::: 

::: {#nte-ctl14 .callout-note title="Other controls section of example `model.ctl` file."}

```default
## ———————————————————————————————————————————————————————————————————————————————————— ##
## OTHER CONTROLS                                          
## ———————————————————————————————————————————————————————————————————————————————————— ##
1982       # First rec_dev                                          
2022       # last rec_dev
   1       # Terminal molting (0 = off, 1 = on). If on, the calc_stock_recruitment_relationship() isn't called in the procedure
   1       # Estimated rec_dev phase  
   2       # Estimated sex_ratio phase
   0.5     # Initial sex ratio
  -3       # Estimated rec_ini phase                                          
   2       # Initial conditions (0 = Unfished, 1 = Steady-state fished, 2 = Free parameters, 3 = Free parameters (revised))
   1       # Lambda (proportion of mature male biomass for SPR reference points).                                          
   0       # Stock-Recruit-Relationship (0 = none, 1 = Beverton-Holt)"                                          
   0       # Use average sex ratio for computing recruitment for reference points (0 = off, i.e. Rec based on End year, 1 = on)
 200       # Years to compute equilibria                                      
```

::: 

::: {#nte-ctl15 .callout-note title="Emphasis factors section of example `model.ctl` file."}

```default
## ———————————————————————————————————————————————————————————————————————————————————— ##
## EMPHASIS FACTORS (CATCH)                                          
## ———————————————————————————————————————————————————————————————————————————————————— ##
#Ret_male Disc_male Disc_female Disc_trawl                                           
   1         1           1          1                                                
## ———————————————————————————————————————————————————————————————————————————————————— ##
## EMPHASIS FACTORS (Priors) by fleet: fdev_total, Fdov_total, Fdev_year, Fdov_year       
## ———————————————————————————————————————————————————————————————————————————————————— ##
#
 1 1 0 0 # Pot_Fishery 
 1 0 0 0 # Trawl_Bycatch
 0 0 0 0 # NMFS_Trawl_1982 
 0 0 0 0 # NMFS_Trawl_1989
#
## ———————————————————————————————————————————————————————————————————————————————————— ##
## EMPHASIS FACTORS (Priors)                                          
## ———————————————————————————————————————————————————————————————————————————————————— ##
# Log_fdevs   meanF  Mdevs  Rec_devs Initial_devs Fst_dif_dev Mean_sex-Ratio  Molt_prob  Free selectivity  Init_n_at_len  Fdevs  Fdovs
#    10000      0     1         1       15           1             3           60            3                  5  
#    10000      0     1         1       15           1             3           60            3                  5           0    0      
10000  # Log_fdevs
0      # meanF  
1      # Mdevs
1      # Rec_devs 
15     # Initial_devs
1      # Fst_dif_dev
3      # Mean_sex-Ratio
60     # Molt_prob
3      # Free selectivity
5      # Init_n_at_len
0      # Fdevs
0      # Fdovs
0      # Sel_devs    
9999 ## EOF                                          
```

::: 

::: {#nte-ctl16 .callout-note title="?? section of example `model.ctl` file."}

```default
```

::: 

::: {#nte-ctl17 .callout-note title="?? section of example `model.ctl` file."}

```default
```

::: 

